In [3]:
#1) Utiliser la méthode Series.values_count() pour afficher le décompte du nombre de zones d’emploies par département
import pandas as pd
import numpy as np 

path='Téléchargements//dossier_simplon_chomage//chomage_zone.xls'
liste_feuille='txcho_ze'

data=pd.read_excel('Téléchargements//dossier_simplon_chomage//chomage_zone.xls', sheet_name=liste_feuille, skiprows=5) 
data

,ZE2010,LIBZE2010,REG,LIBREG,2003-T1,2003-T2,2003-T3,2003-T4,2004-T1,2004-T2,...,2017-T4,2018-T1,2018-T2,2018-T3,2018-T4,2019-T1,2019-T2,2019-T3,2019-T4,2020-T1
0,0050,Mont-de-Marsan,0.0,interrégional,6.0,6.1,6.0,6.3,6.4,6.2,...,7.3,7.4,7.1,7.0,6.7,6.8,6.7,6.7,6.5,6.1
1,0051,Alençon,0.0,interrégional,7.2,7.5,7.2,7.6,7.7,7.4,...,8.3,8.6,8.4,8.4,8.1,8.1,7.9,7.9,7.8,7.4
2,0052,Cosne-Clamecy,0.0,interrégional,7.5,7.6,7.4,7.8,8.0,7.7,...,8.1,8.3,8.1,7.9,7.5,7.5,7.2,7.4,7.2,6.8
3,0053,Mâcon,0.0,interrégional,5.3,5.3,5.2,5.3,5.4,5.4,...,6.4,6.5,6.5,6.4,6.3,6.4,6.3,6.3,6.1,5.9
4,0054,Nogent-le-Rotrou,0.0,interrégional,5.9,6.3,6.4,7.0,7.3,7.2,...,8.1,8.3,8.1,8.0,7.9,7.9,7.8,8.0,7.4,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300,9404,Bastia,94.0,Corse,9.2,8.9,8.9,9.3,9.4,9.3,...,9.7,10.1,9.7,9.4,9.2,9.2,8.8,8.5,8.2,7.9
301,9405,Calvi-L'Île-Rousse,94.0,Corse,11.7,11.4,11.2,11.4,11.2,11.5,...,11.6,12.5,12.2,11.9,11.4,11.6,11.0,10.8,10.5,10.1
302,9406,Corte,94.0,Corse,8.3,7.6,8.2,8.1,8.0,8.0,...,8.5,8.9,8.9,8.6,7.8,8.2,7.6,7.3,7.1,7.3
303,9407,Ghisonaccia-Aléria,94.0,Corse,9.6,8.8,9.0,9.4,9.6,9.7,...,10.0,10.6,10.4,10.1,9.9,10.0,9.4,9.4,9.0,8.6
304,"Source : Insee, Estimations de taux de chômage...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
data['REG'].value_counts()

84.0    35
75.0    31
44.0    31
76.0    30
32.0    26
27.0    23
28.0    20
52.0    19
24.0    19
11.0    19
53.0    18
93.0    17
0.0      9
94.0     7
Name: REG, dtype: int64

In [6]:
data[['REG','LIBZE2010']].groupby(['REG']).count()  #méthode alternative

      LIBZE2010
REG
0.0           9
11.0         19
24.0         19
27.0         23
28.0         20
32.0         26
44.0         31
52.0         19
53.0         18
75.0         31
76.0         30
84.0         35
93.0         17
94.0          7

In [63]:
# 2) Filtrer et garder toute les ligne du dataframepour lesquelles le département est «Provence-Alpes-Côte d'Azur»

data.loc[data['LIBREG']=="Provence-Alpes-Côte d'Azur"]

,ZE2010,LIBZE2010,REG,LIBREG,2003-T1,2003-T2,2003-T3,2003-T4,2004-T1,2004-T2,...,2017-T4,2018-T1,2018-T2,2018-T3,2018-T4,2019-T1,2019-T2,2019-T3,2019-T4,2020-T1
280,9301,Digne-les-Bains,93.0,Provence-Alpes-Côte d'Azur,7.5,7.6,7.2,7.6,7.7,7.5,...,10.7,11.0,10.7,10.6,10.4,10.3,10.0,9.8,9.4,9.1
281,9302,Manosque,93.0,Provence-Alpes-Côte d'Azur,10.0,10.1,9.8,9.8,9.9,9.7,...,11.2,11.6,11.4,11.1,10.9,11.0,10.6,10.5,10.0,9.6
282,9303,Briançon,93.0,Provence-Alpes-Côte d'Azur,7.0,7.1,7.0,7.4,7.4,7.4,...,8.2,8.4,8.3,8.4,8.2,8.3,8.3,8.0,7.9,7.5
283,9304,Gap,93.0,Provence-Alpes-Côte d'Azur,7.0,7.0,6.9,7.1,7.3,7.1,...,8.2,8.3,8.3,8.2,8.0,8.0,7.7,7.5,7.2,7.0
284,9305,Cannes-Antibes,93.0,Provence-Alpes-Côte d'Azur,9.5,9.7,9.4,9.5,9.5,9.3,...,9.8,10.1,9.9,9.7,9.5,9.5,9.1,9.1,8.7,8.5
285,9306,Menton Vallée de la Roya,93.0,Provence-Alpes-Côte d'Azur,6.8,6.9,6.7,6.9,6.9,6.7,...,8.3,8.4,8.1,7.8,7.6,7.6,7.3,7.2,6.9,6.7
286,9307,Nice,93.0,Provence-Alpes-Côte d'Azur,8.1,8.1,8.0,8.3,8.3,8.1,...,9.6,9.8,9.6,9.5,9.2,9.2,8.9,8.9,8.4,8.2
287,9308,Aix-en-Provence,93.0,Provence-Alpes-Côte d'Azur,9.2,9.4,9.2,9.3,9.4,9.0,...,8.4,8.6,8.5,8.3,8.1,8.0,7.7,7.7,7.3,7.0
288,9309,Arles,93.0,Provence-Alpes-Côte d'Azur,11.1,11.4,11.1,11.4,11.5,11.0,...,12.4,12.5,12.5,12.3,11.7,11.8,11.4,11.4,11.0,10.7
289,9310,Marseille-Aubagne,93.0,Provence-Alpes-Côte d'Azur,11.6,11.8,11.4,11.6,11.7,11.3,...,11.5,11.9,11.7,11.6,11.2,11.2,10.8,10.7,10.3,9.9
290,9311,Istres-Martigues,93.0,Provence-Alpes-Côte d'Azur,10.3,10.5,10.3,10.5,10.5,10.2,...,10.8,11.1,10.8,10.7,10.2,10.3,10.1,9.9,9.6,9.2
291,9312,Salon-de-Provence,93.0,Provence-Alpes-Côte d'Azur,10.7,10.8,10.4,10.6,10.7,10.3,...,10.4,10.6,10.4,10.3,10.0,10.0,9.7,9.5,9.1,8.7
292,9313,Draguignan,93.0,Provence-Alpes-Côte d'Azur,11.4,11.4,11.2,11.4,11.3,11.1,...,11.6,12.0,11.8,11.5,11.2,11.2,10.9,10.8,10.2,9.8
293,9314,Fréjus-Saint Raphaël,93.0,Provence-Alpes-Côte d'Azur,10.0,10.1,10.1,10.6,10.9,11.0,...,11.7,12.2,11.9,11.7,11.5,11.5,11.1,11.0,10.5,10.3
294,9315,Toulon,93.0,Provence-Alpes-Côte d'Azur,10.6,10.6,10.3,10.5,10.6,10.4,...,9.5,9.7,9.6,9.5,9.3,9.3,8.9,8.8,8.4,8.1
295,9316,Cavaillon-Apt,93.0,Provence-Alpes-Côte d'Azur,9.3,9.2,8.9,9.1,9.1,9.0,...,11.9,12.1,11.9,11.8,11.4,11.7,11.2,11.2,10.7,10.3
296,9317,Orange,93.0,Provence-Alpes-Côte d'Azur,9.7,9.6,9.2,9.3,9.4,9.3,...,12.0,12.2,12.1,12.0,11.7,11.6,11.3,11.2,10.5,10.1

In [8]:
#3) Assigner ce nouveau dataframeà data2 et afficher le.

data2=data.loc[data['LIBREG']=="Provence-Alpes-Côte d'Azur"]
print(data2)

    ZE2010                 LIBZE2010   REG                      LIBREG  \
280   9301           Digne-les-Bains  93.0  Provence-Alpes-Côte d'Azur
281   9302                  Manosque  93.0  Provence-Alpes-Côte d'Azur
282   9303                  Briançon  93.0  Provence-Alpes-Côte d'Azur
283   9304                       Gap  93.0  Provence-Alpes-Côte d'Azur
284   9305            Cannes-Antibes  93.0  Provence-Alpes-Côte d'Azur
285   9306  Menton Vallée de la Roya  93.0  Provence-Alpes-Côte d'Azur
286   9307                      Nice  93.0  Provence-Alpes-Côte d'Azur
287   9308           Aix-en-Provence  93.0  Provence-Alpes-Côte d'Azur
288   9309                     Arles  93.0  Provence-Alpes-Côte d'Azur
289   9310         Marseille-Aubagne  93.0  Provence-Alpes-Côte d'Azur
290   9311          Istres-Martigues  93.0  Provence-Alpes-Côte d'Azur
291   9312         Salon-de-Provence  93.0  Provence-Alpes-Côte d'Azur
292   9313                Draguignan  93.0  Provence-Alpes-Côte d'Azur
293   9314      Fréjus-Saint Raphaël  93.0  Provence-Alpes-Côte d'Azur
294   9315                    Toulon  93.0  Provence-Alpes-Côte d'Azur
295   9316             Cavaillon-Apt  93.0  Provence-Alpes-Côte d'Azur
296   9317                    Orange  93.0  Provence-Alpes-Côte d'Azur

     2003-T1  2003-T2  2003-T3  2003-T4  2004-T1  2004-T2  ...  2017-T4  \
280      7.5      7.6      7.2      7.6      7.7      7.5  ...     10.7
281     10.0     10.1      9.8      9.8      9.9      9.7  ...     11.2
282      7.0      7.1      7.0      7.4      7.4      7.4  ...      8.2
283      7.0      7.0      6.9      7.1      7.3      7.1  ...      8.2
284      9.5      9.7      9.4      9.5      9.5      9.3  ...      9.8
285      6.8      6.9      6.7      6.9      6.9      6.7  ...      8.3
286      8.1      8.1      8.0      8.3      8.3      8.1  ...      9.6
287      9.2      9.4      9.2      9.3      9.4      9.0  ...      8.4
288     11.1     11.4     11.1     11.4     11.5     11.0  ...     12.4
289     11.6     11.8     11.4     11.6     11.7     11.3  ...     11.5
290     10.3     10.5     10.3     10.5     10.5     10.2  ...     10.8
291     10.7     10.8     10.4     10.6     10.7     10.3  ...     10.4
292     11.4     11.4     11.2     11.4     11.3     11.1  ...     11.6
293     10.0     10.1     10.1     10.6     10.9     11.0  ...     11.7
294     10.6     10.6     10.3     10.5     10.6     10.4  ...      9.5
295      9.3      9.2      8.9      9.1      9.1      9.0  ...     11.9
296      9.7      9.6      9.2      9.3      9.4      9.3  ...     12.0

     2018-T1  2018-T2  2018-T3  2018-T4  2019-T1  2019-T2  2019-T3  2019-T4  \
280     11.0     10.7     10.6     10.4     10.3     10.0      9.8      9.4
281     11.6     11.4     11.1     10.9     11.0     10.6     10.5     10.0
282      8.4      8.3      8.4      8.2      8.3      8.3      8.0      7.9
283      8.3      8.3      8.2      8.0      8.0      7.7      7.5      7.2
284     10.1      9.9      9.7      9.5      9.5      9.1      9.1      8.7
285      8.4      8.1      7.8      7.6      7.6      7.3      7.2      6.9
286      9.8      9.6      9.5      9.2      9.2      8.9      8.9      8.4
287      8.6      8.5      8.3      8.1      8.0      7.7      7.7      7.3
288     12.5     12.5     12.3     11.7     11.8     11.4     11.4     11.0
289     11.9     11.7     11.6     11.2     11.2     10.8     10.7     10.3
290     11.1     10.8     10.7     10.2     10.3     10.1      9.9      9.6
291     10.6     10.4     10.3     10.0     10.0      9.7      9.5      9.1
292     12.0     11.8     11.5     11.2     11.2     10.9     10.8     10.2
293     12.2     11.9     11.7     11.5     11.5     11.1     11.0     10.5
294      9.7      9.6      9.5      9.3      9.3      8.9      8.8      8.4
295     12.1     11.9     11.8     11.4     11.7     11.2     11.2     10.7
296     12.2     12.1     12.0     11.7     11.6     11.3     11.2     10.5

     2020-T1
280      9.1
281      9.6
282      7.5
283      7.0
284      8.5
285      6.7
286      8.2
287      7.0
288     10.7
289      9.9
290      9.2
291      8.7
292      9.8
293     10.3
294      8.1
295     10.3
296     10.1

[17 rows x 73 columns]

In [9]:
# 4) Utiliser la méthode Series.values_count() pour afficher combien de fois une zone d’emploie apparait en «Provence-Alpes-Côte d'Azur »

data2['LIBZE2010'].value_counts()

Marseille-Aubagne           1
Arles                       1
Cavaillon-Apt               1
Cannes-Antibes              1
Istres-Martigues            1
Draguignan                  1
Nice                        1
Digne-les-Bains             1
Menton Vallée de la Roya    1
Orange                      1
Briançon                    1
Aix-en-Provence             1
Gap                         1
Toulon                      1
Fréjus-Saint Raphaël        1
Salon-de-Provence           1
Manosque                    1
Name: LIBZE2010, dtype: int64

data2[['LIBZE2010','ZE2010']].groupby('LIBZE2010').count() #methode alternative

In [57]:
# 5) Créer un objet indiquant avec des booléens si le taux de chômage pour le 1ere trimestre 2020 est supérieur à 7.1Assigner le résultat à la variable «data_t1_2020»

data_T1_2020=data['2020-T1']>7.1
print(data_T1_2020)

0      False
1       True
2      False
3      False
4      False
       ...
300     True
301     True
302     True
303     True
304    False
Name: 2020-T1, Length: 305, dtype: bool

In [58]:
# 6) Créer un objet indiquant avec des booléens si le taux de chômage pour le 1ere trimestre 2019 est supérieur à 7.1. Assigner le résultat à la variable «data_t1_2019»

data_T1_2019=data['2019-T1']>7.1
print(data_T1_2019)

0      False
1       True
2       True
3      False
4       True
       ...
300     True
301     True
302     True
303     True
304    False
Name: 2019-T1, Length: 305, dtype: bool

In [59]:
# 7) Créer un objet indiquant avec des booléens si le taux de chômage pour le 1ere trimestre 2018 est supérieur à 7.1 .Assigner le résultat à la variable «data_t1_2019»

data_T1_2018=data['2018-T1']>7.1
print(data_T1_2018)

0       True
1       True
2       True
3      False
4       True
       ...
300     True
301     True
302     True
303     True
304    False
Name: 2018-T1, Length: 305, dtype: bool

In [13]:
#8) Combiner les trois objets Seriesavec l’operateur «&» et assigné le résultat à la variable «data_7_1» .

data_7_1= data_T1_2018 & data_T1_2019 & data_T1_2020
print(data_7_1)

0      False
1       True
2      False
3      False
4      False
       ...
300     True
301     True
302     True
303     True
304    False
Length: 305, dtype: bool

In [60]:
#9) data_7_1 est une liste. Assigné là à un dataframedont le nom de colonne sera «booleen»

dataframe1=pd.DataFrame(data_7_1, columns=['booleen'])
print(dataframe1)

     booleen
0      False
1       True
2      False
3      False
4      False
..       ...
300     True
301     True
302     True
303     True
304    False

[305 rows x 1 columns]

In [15]:
# 10) Afficher les valeurs unique et combien de fois elle apparaissent dans la colonnes

dataframe1['booleen'].value_counts(sort=True).head(20)

True     163
False    142
Name: booleen, dtype: int64

In [16]:
# 11)Charger le fichier «pole_emploi.xlsx» après l’avoir ouvert et visualiser et l’assigner à la variable «p_emploi»

path='Téléchargements/dossier_simplon_chomage/pole_emploi.xlsx'
p_emploi=pd.read_excel(path,skiprows=3, columns=['code','libellé','P_E_2018'])
p_emploi.rename(columns={'Code':'REG','Libellé':'libellé', 'Pôle emploi 2018':'p_e_2018'}, inplace=True)
print(p_emploi)

    REG                     libellé  p_e_2018
0     1                  Guadeloupe        17
1     2                  Martinique        11
2     3                      Guyane         8
3     4                  La Réunion        17
4     6                     Mayotte         3
5    11               Île-de-France       164
6    24         Centre-Val de Loire       116
7    27     Bourgogne-Franche-Comté       165
8    28                   Normandie       145
9    32             Hauts-de-France       171
10   44                   Grand Est       238
11   52            Pays de la Loire       104
12   53                    Bretagne        91
13   75          Nouvelle-Aquitaine       251
14   76                   Occitanie       262
15   84        Auvergne-Rhône-Alpes       294
16   93  Provence-Alpes-Côte d'Azur       145
17   94                       Corse        31

In [20]:
# 12) Joindre les data et p_emploiau seins d’un seul et unique dataframeen faisant correspondre les régions par leur codes. Utiliser pd.merge() pour réaliser cette jointure 

p_emploi.sort_values(by=['REG'])
data.sort_values('REG')
data_combo=p_emploi.merge(data, how='right')
print(data_combo[['REG','p_e_2018']].tail(50))

      REG  p_e_2018
255  84.0     294.0
256  84.0     294.0
257  84.0     294.0
258  84.0     294.0
259  84.0     294.0
260  84.0     294.0
261  84.0     294.0
262  84.0     294.0
263  84.0     294.0
264  84.0     294.0
265  84.0     294.0
266  84.0     294.0
267  84.0     294.0
268  84.0     294.0
269  84.0     294.0
270  84.0     294.0
271  93.0     145.0
272  93.0     145.0
273  93.0     145.0
274  93.0     145.0
275  93.0     145.0
276  93.0     145.0
277  93.0     145.0
278  93.0     145.0
279  93.0     145.0
280  93.0     145.0
281  93.0     145.0
282  93.0     145.0
283  93.0     145.0
284  93.0     145.0
285  93.0     145.0
286  93.0     145.0
287  93.0     145.0
288  94.0      31.0
289  94.0      31.0
290  94.0      31.0
291  94.0      31.0
292  94.0      31.0
293  94.0      31.0
294  94.0      31.0
295   0.0       NaN
296   0.0       NaN
297   0.0       NaN
298   0.0       NaN
299   0.0       NaN
300   0.0       NaN
301   0.0       NaN
302   0.0       NaN
303   0.0       NaN
304   NaN       NaN

In [328]:
#13) créer une colonne quantile dans p_emploi qui prendra les valeurs ['q25','q50','q75','q100'] en fonction du quartile auquel appartient le nombre de pôle emploi .pour se faire, utiliser "pd.qcut()"

liste_quantile=['q25','q50','q75','q100']
data_combo['quantile']=pd.qcut(data_combo['p_e_2018'],4,labels=liste_quantile )
data_combo['quantile'].head(50)

0     q50
1     q50
2     q50
3     q50
4     q50
5     q50
6     q50
7     q50
8     q50
9     q50
10    q50
11    q50
12    q50
13    q50
14    q50
15    q50
16    q50
17    q50
18    q50
19    q25
20    q25
21    q25
22    q25
23    q25
24    q25
25    q25
26    q25
27    q25
28    q25
29    q25
30    q25
31    q25
32    q25
33    q25
34    q25
35    q25
36    q25
37    q25
38    q50
39    q50
40    q50
41    q50
42    q50
43    q50
44    q50
45    q50
46    q50
47    q50
48    q50
49    q50
Name: quantile, dtype: category
Categories (4, object): [q25 < q50 < q75 < q100]

In [61]:
14#)Générer un pivot de table montrant la moyenne du taux de chômage du trimestre 1 de l’année 2020 pour chaque régions et quantile du nombre de pôle emploi.

table=pd.pivot_table( data_combo,index=['LIBREG'],columns=['quantile'] ,values=['2020-T1'],aggfunc={'2020-T1':np.nanmean }  )   
print(table)

                             2020-T1
quantile                         q25       q50       q75      q100
LIBREG
Auvergne-Rhône-Alpes             NaN       NaN       NaN  6.728571
Bourgogne-Franche-Comté          NaN  6.565217       NaN       NaN
Bretagne                    6.661111       NaN       NaN       NaN
Centre-Val-de-Loire         7.684211       NaN       NaN       NaN
Corse                       8.514286       NaN       NaN       NaN
Grand-Est                        NaN       NaN  7.264516       NaN
Hauts-de-France                  NaN  9.911538       NaN       NaN
Ile-de-France                    NaN  6.794737       NaN       NaN
Normandie                   7.150000       NaN       NaN       NaN
Nouvelle-Aquitaine               NaN       NaN  7.293548       NaN
Occitanie                        NaN       NaN       NaN  9.603333
Pays de la Loire            6.563158       NaN       NaN       NaN
Provence-Alpes-Côte d'Azur  8.864706       NaN       NaN       NaN

In [62]:
#) expérimentation récréative
table2=pd.pivot_table( data_combo,index=['LIBREG'],columns=['quantile'] ,values=['2020-T1'],aggfunc={'2020-T1':np.sum }  )
print(table2)

                           2020-T1
quantile                       q25    q50    q75   q100
LIBREG
Auvergne-Rhône-Alpes           NaN    NaN    NaN  235.5
Bourgogne-Franche-Comté        NaN  151.0    NaN    NaN
Bretagne                     119.9    NaN    NaN    NaN
Centre-Val-de-Loire          146.0    NaN    NaN    NaN
Corse                         59.6    NaN    NaN    NaN
Grand-Est                      NaN    NaN  225.2    NaN
Hauts-de-France                NaN  257.7    NaN    NaN
Ile-de-France                  NaN  129.1    NaN    NaN
Normandie                    143.0    NaN    NaN    NaN
Nouvelle-Aquitaine             NaN    NaN  226.1    NaN
Occitanie                      NaN    NaN    NaN  288.1
Pays de la Loire             124.7    NaN    NaN    NaN
Provence-Alpes-Côte d'Azur   150.7    NaN    NaN    NaN